# AdvancedEnchantments
# Made by AdvancedPlugins.net
# Config Version: @version@
# Version Release date: @date@

# Homepage: https://advancedplugins.net/item/AdvancedSeasons.185/
# Wiki: https://seasons.advancedplugins.net/

# Change default messages language. You can modify all messages in AdvancedSeasons `lang` folder.
locale: en

# Should temperature be converted to Fahrenheit?
# If true, temperature will be displayed in Fahrenheit, but all calculations will be done in Celsius
# If false, temperature will be displayed in Celsius, and all calculations will be done in Celsius
convertToFahrenheit: false

# World List.
# List of worlds where AdvancedSeasons should be enabled
# You can add worlds in-game using '/as addworld <world name>' command
worlds: []

# Should temperature effects be given to creative players?
creativeTemperatureEffects: false

# Should land protection plugins be ignored?
# If true, AdvancedSeasons will ignore land protection plugins and will be able to change blocks in protected areas
# This may have impact on performance depending on land protection plugins
ignoreLandProtection: false

# Should snow generate in winter?
snowEnabled: true

# Block processing around player
# Default is 9 chunks, which means 9x9 chunks around player will be checked for snow/grass etc.
# We recommend leaving the setting as default. For performance issues, you can lower the value. Increasing it may
# cause more strain on the server, however it is very optimized, uses async and multithreading, so it's able to handle more.
chunkRadius: 9

# When seasons change, how many chunks updates should be sent out to each player every second?
# Default is 8, which means 8 chunks will be updated every second. This only affects surrounding area of the player.
# 8 is a very safe value, and chunks around the player will update gradually. Having a bigger number may overload
# the player connection, and could cause kicks or freezes. If you are experiencing any problems like those, lower the value.
chunkUpdates: 8

# Is temperature actionbar enabled?
# If true, temperature will be displayed in actionbar
# Even if set to false, temperature events will show in actionbar
temperatureActionbar: true

# Should temperature events be shown in actionbar?
# If true, temperature events will be shown in actionbar
temperatureEventsActionbar: true

